//
//  FavoritePresenterTests.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/21/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SpaceX
import XCTest

class FavoritePresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: FavoritePresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupFavoritePresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupFavoritePresenter()
  {
    sut = FavoritePresenter()
  }
  
  // MARK: Test doubles
  
  class FavoriteDisplayLogicSpy: FavoriteDisplayLogic
  {
    var displaySomethingCalled = false
    
      func displayRocketList(viewModel: Favorite.getFavoriteList.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = FavoriteDisplayLogicSpy()
    sut.viewController = spy
      let response = Favorite.getFavoriteList.Response(rocketList: [])
    
    // When
      sut.presentRoketList(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
