//
//  FavoriteInteractorTests.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/21/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SpaceX
import XCTest

class FavoriteInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: FavoriteInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupFavoriteInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupFavoriteInteractor()
  {
    sut = FavoriteInteractor()
  }
  
  // MARK: Test doubles
  
  class FavoritePresentationLogicSpy: FavoritePresentationLogic
  {
    var presentSomethingCalled = false
    
      func presentRoketList(response: Favorite.getFavoriteList.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = FavoritePresentationLogicSpy()
    sut.presenter = spy
      let request = Favorite.getFavoriteList.Request()
    
    // When
      sut.getRockestList(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
