//
//  RocketDetailPresenterTests.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/21/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SpaceX
import XCTest

class RocketDetailPresenterTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: RocketDetailPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupRocketDetailPresenter()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupRocketDetailPresenter()
    {
        sut = RocketDetailPresenter()
    }
    
    // MARK: Test doubles
    
    class RocketDetailDisplayLogicSpy: RocketDetailDisplayLogic
    {
        var displayDetailCalled = false
        
        func displayDetail(viewModel: RocketDetail.Roket.ViewModel)
        {
            displayDetailCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentSomething()
    {
        // Given
        let spy = RocketDetailDisplayLogicSpy()
        sut.viewController = spy
        let response = RocketDetail.Roket.Response(rocket: Seeds.Rockets.rocket1)
        
        // When
        sut.presentDetail(response: response)
        
        // Then
        XCTAssertTrue(spy.displayDetailCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
