//
//  RocketDetailInteractor.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RocketDetailBusinessLogic
{
  func doSomething(request: RocketDetail.Something.Request)
}

protocol RocketDetailDataStore
{
  //var name: String { get set }
}

class RocketDetailInteractor: RocketDetailBusinessLogic, RocketDetailDataStore
{
  var presenter: RocketDetailPresentationLogic?
  var worker: RocketDetailWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: RocketDetail.Something.Request)
  {
    worker = RocketDetailWorker()
    worker?.doSomeWork()
    
    let response = RocketDetail.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
