//
//  RocketDetailModels.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RocketDetail
{
  // MARK: Use cases
  
  enum Roket
  {
    struct Request
    {
        var id: String
    }
    struct Response
    {
        var rocket: Rocket
    }
    struct ViewModel
    {
        struct DisplatRocket {
            var id : String
            var name : String
            var description : String
            var flickr_images : [String]
            var country: String
            var company: String
        }
        var displayRocket: DisplatRocket
    }
  }
}
