//
//  FavoriteModels.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/20/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Favorite
{
  // MARK: Use cases
  
  enum getFavoriteList
  {
    struct Request
    {
    }
    struct Response
    {
        var rocketList: [Rocket]
    }
      struct ViewModel
      {
          struct DisplayRocketList {
              var id : String
              var name : String
              var description : String
              var flickr_images : [String]
          }
          var displayRocketList: [DisplayRocketList]
      }
  }
}
