//
//  FavoritePresenter.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/20/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoritePresentationLogic
{
    func presentRoketList(response: Favorite.getFavoriteList.Response)
}

class FavoritePresenter: FavoritePresentationLogic
{
  weak var viewController: FavoriteDisplayLogic?
  
  // MARK: Do something
  
    func presentRoketList(response: Favorite.getFavoriteList.Response)
  {
      var list: [Favorite.getFavoriteList.ViewModel.DisplayRocketList] = []
      for rocket in response.rocketList {
          let model = Favorite.getFavoriteList.ViewModel.DisplayRocketList(id: rocket.id ?? "", name: rocket.name ?? "", description: rocket.description ?? "", flickr_images: rocket.flickrImages ?? [])
          list.append(model)
      }
      let viewModel = Favorite.getFavoriteList.ViewModel(displayRocketList: list)
      viewController?.displayRocketList(viewModel: viewModel)
  }
}
