//
//  FavoriteRouter.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/20/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FavoriteRoutingLogic
{
    func routeToRocketDetail(segue: UIStoryboardSegue?, sender: Any)
}

protocol FavoriteDataPassing
{
  var dataStore: FavoriteDataStore? { get }
}

class FavoriteRouter: NSObject, FavoriteRoutingLogic, FavoriteDataPassing
{
  weak var viewController: FavoriteViewController?
  var dataStore: FavoriteDataStore?
  
  // MARK: Routing
  
    func routeToRocketDetail(segue: UIStoryboardSegue?, sender: Any) {
        if let segue = segue {
            let destinationVC = segue.destination as! RocketDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            let dict = sender as? [String:AnyObject]
            if let detailId = (dict?["id"]) as? String {
                passDataTodetail(source: dataStore!, destination: &destinationDS, id: detailId)
            }
        }
    }

  // MARK: Navigation
  
  //func navigateToSomewhere(source: FavoriteViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
    func passDataTodetail(source: FavoriteDataStore, destination: inout RocketDetailDataStore, id: String)
  {
      destination.id = id
  }
}
