//
//  FavoriteInteractor.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/20/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FavoriteBusinessLogic
{
    func getRockestList(request: Favorite.getFavoriteList.Request)
}

protocol FavoriteDataStore
{
    var rocketList : [Rocket]? {get}
}

class FavoriteInteractor: FavoriteBusinessLogic, FavoriteDataStore
{
    var rocketList: [Rocket]?
    var presenter: FavoritePresentationLogic?
    var worker = RocketWorker()
    
    // MARK: Do something
    
    func getRockestList(request: Favorite.getFavoriteList.Request)
    {
        worker.getRocketList(completionHandler: { response in
            let allFavorite = Defaults.shared.getRockets()
            let filter = response.filter{ allFavorite.contains($0.id ?? "") }
            let response = Favorite.getFavoriteList.Response(rocketList: filter)
            self.presenter?.presentRoketList(response: response)
        }, failure: { (error) in
            print(error)
        })
    }
}
