//
//  RocketListPresenterTests.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/20/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SpaceX
import XCTest

class RocketListPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: RocketListPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupRocketListPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupRocketListPresenter()
  {
    sut = RocketListPresenter()
  }
  
  // MARK: Test doubles
  
  class RocketListDisplayLogicSpy: RocketListDisplayLogic
    {
      
    var displayRocketCalled = false
    
      func displayRocketList(viewModel: RocketList.getRocketList.ViewModel)
    {
        displayRocketCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = RocketListDisplayLogicSpy()
    sut.viewController = spy
      let response = RocketList.getRocketList.Response(rocketList: [])
    
    // When
      sut.presentRoketList(response: response)
    
    // Then
      XCTAssertTrue(spy.displayRocketCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
