//
//  RocketListInteractorTests.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/20/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SpaceX
import XCTest

class RocketListInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: RocketListInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupRocketListInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupRocketListInteractor()
  {
    sut = RocketListInteractor()
  }
  
  // MARK: Test doubles
  
  class RocketListPresentationLogicSpy: RocketListPresentationLogic
    {
      var presentRocketCalled = false
      
      func presentRoketList(response: RocketList.getRocketList.Response) {
          presentRocketCalled = true
      }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = RocketListPresentationLogicSpy()
    sut.presenter = spy
      let request = RocketList.getRocketList.Request()
    
    // When
      sut.getRockestList(request: request)
    
    // Then
      XCTAssertTrue(spy.presentRocketCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
