//
//  RocketListInteractor.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RocketListBusinessLogic
{
    func getRockestList(request: RocketList.getRocketList.Request)
}

protocol RocketListDataStore
{
    var rocketList : [Rocket]? {get}
}

class RocketListInteractor: RocketListBusinessLogic, RocketListDataStore
{
    
    var rocketList: [Rocket]?
    var presenter: RocketListPresentationLogic?
    var worker = RocketWorker()
    //var name: String = ""
    
    // MARK: Do something
    
    func getRockestList(request: RocketList.getRocketList.Request)
    {
        worker.getRocketList(completionHandler: { response in
            let response = RocketList.getRocketList.Response(rocketList: response)
            self.presenter?.presentRoketList(response: response)
        }, failure: { (error) in
            print(error)
        })
    }
}
