//
//  RocketListRouter.swift
//  SpaceX
//
//  Created by habib Ghaffarzadeh on 2/19/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RocketListRoutingLogic
{
    func routeToRocketDetail(segue: UIStoryboardSegue?)
}

protocol RocketListDataPassing
{
    var dataStore: RocketListDataStore? { get }
}

class RocketListRouter: NSObject, RocketListRoutingLogic, RocketListDataPassing
{
    weak var viewController: RocketListViewController?
    var dataStore: RocketListDataStore?
    
    // MARK: Routing
    
    func routeToRocketDetail(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! RocketDetailViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataTodetail(source: dataStore!, destination: &destinationDS)
        }
    }

  // MARK: Navigation
  
  //func navigateToSomewhere(source: RocketListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  func passDataTodetail(source: RocketListDataStore, destination: inout RocketDetailDataStore)
  {
      //destination.name = source.name
  }
}
